version: '3.7'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: chatwoot
      POSTGRES_USER: chatwoot
      POSTGRES_PASSWORD: supersecurepassword
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - chatwoot-net

  redis:
    image: redis:7
    restart: always
    volumes:
      - ./data/redis:/data
    networks:
      - chatwoot-net

  chatwoot:
    image: chatwoot/chatwoot:latest
    restart: always
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: "true"
      RAILS_SERVE_STATIC_FILES: "true"
      SECRET_KEY_BASE: changemechatwootkey
      FRONTEND_URL: https://chat.aposistemas.com.br
      POSTGRES_HOST: postgres
      POSTGRES_DATABASE: chatwoot
      POSTGRES_USERNAME: chatwoot
      POSTGRES_PASSWORD: supersecurepassword
      REDIS_URL: redis://redis:6379
      INSTALLATION_ENV: docker
      ENABLE_ACCOUNT_SIGNUP: "true"
    depends_on:
      - postgres
      - redis
    networks:
      - chatwoot-net
    # Sem porta exposta aqui 👇
    expose:
      - "3000"

  sidekiq:
    image: chatwoot/chatwoot:latest
    restart: always
    command: bundle exec sidekiq
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: changemechatwootkey
      POSTGRES_HOST: postgres
      POSTGRES_DATABASE: chatwoot
      POSTGRES_USERNAME: chatwoot
      POSTGRES_PASSWORD: supersecurepassword
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - chatwoot-net

networks:
  chatwoot-net:
    driver: bridge
