version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=arthurp
      - N8N_BASIC_AUTH_PASSWORD=password
      - N8N_HOST=n8n.local
      - N8N_PORT=5678
      - WEBHOOK_URL=https://n8n.aposistemas.com.br/
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - n8n_internal
    # sem a exposição da porta!

volumes:
  n8n_data:

networks:
  n8n_internal:
    driver: bridge